server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dms?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.equipment.management.pojo
