server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.10.211:3306/db_device?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: guxinyu
    password: 123456
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.equipment.management.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
